# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cda0c05e2b5a180ba45eea5686806b75"
name = "strategic-outsource-app"
handle = "strategic-outsource-app-2"
application_url = "https://confused-wishing-wr-pts.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "komuta-test.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://confused-wishing-wr-pts.trycloudflare.com/auth/callback",
  "https://confused-wishing-wr-pts.trycloudflare.com/auth/shopify/callback",
  "https://confused-wishing-wr-pts.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
